baseurl: /ACE3

name: ACE3
description: ACE3 is a joint effort by the teams behind ACE2, AGM and CSE to improve the realism and authenticity of Arma 3.

date: 2015-04-15

productionUrl : http://ace3mod.com
githubUrl: https://github.com/acemod/ACE3

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "html_toc"]

timezone: UTC

highlighter: pygments

safe: true
lsi: false

exclude: [src, .editorconfig, .gitignore, CNAME, Gemfile, Gemfile.lock,  README.md, src]
