baseurl: /ACE3

name: ACE3
description: ACE 3 is a joint effort by the teams behind ACE2, AGM and CSE to improve the realism and authenticity of Arma 3.

markdown: redcarpet
redcarpet:
  extensions:
    - with_toc_data
    - html_toc

timezone: UTC

highlighter: pygments

safe: true
lsi: false

exclude: [.editorconfig,README.md, src]
