class CfgGesturesMale
{
	class ManActions;
	class Actions;
	class Default;
	class States
	{
		class MOCAP_Gesture_CombatPace_Rfl_Stroke_RightCurve: Default
		{
			file=QPATHTOF(Gestures\Rfl\MOCAP_Gesture_CombatPace_Rfl_Stroke_RightCurve.rtm);
			looped=0;
			speed=0.80000001;
			duty=1;
			aimingBody="aimingUpDefault";
			mask="handsRflStroke";
			soundOverride="rifle_to_handgun";
			leftHandIKBeg=1;
			leftHandIKCurve[]={1};
			leftHandIKEnd=0;
			rightHandIKBeg=1;
			rightHandIKCurve[]={};
			rightHandIKEnd=1;
			weaponIK=0;
			enableOptics=0;
			showWeaponAim=1;
			disableWeapons=1;
			disableWeaponsLong=1;
			canPullTrigger=0;
		};
		class MOCAP_Gesture_CombatPace_Rfl_Stroke_DirectCurve: Default
		{
			file=QPATHTOF(Gestures\Rfl\MOCAP_Gesture_CombatPace_Rfl_Stroke_DirectCurve.rtm);
			looped=0;
			speed=0.85000002;
			duty=1;
			mask="handsRflStroke";
			aimingBody="aimingUpDefault";
			leftHandIKBeg=1;
			leftHandIKCurve[]={1};
			leftHandIKEnd=1;
			rightHandIKBeg=1;
			rightHandIKCurve[]={};
			rightHandIKEnd=1;
			weaponIK=0;
			enableOptics=0;
			showWeaponAim=1;
			disableWeapons=1;
			disableWeaponsLong=1;
			canPullTrigger=0;
			soundOverride="rifle_to_handgun";
		};
		class MOCAP_Gesture_CombatPace_Pstl_Stroke_RightCurve: Default
		{
			file=QPATHTOF(Gestures\Pstl\MOCAP_Gesture_CombatPace_Pstl_Stroke_RightCurve.rtm);
			looped=0;
			speed=0.89999998;
			duty=1;
			aimingBody="aimingUpDefault";
			mask="handsPstlStroke";
			leftHandIKBeg=1;
			leftHandIKCurve[]={};
			leftHandIKEnd=0;
			rightHandIKBeg=1;
			rightHandIKCurve[]={1};
			rightHandIKEnd=1;
			weaponIK=0;
			enableOptics=0;
			showWeaponAim=0;
			disableWeapons=1;
			disableWeaponsLong=1;
			canPullTrigger=0;
			soundOverride="rifle_to_handgun";
		};
		class MOCAP_Gesture_CombatPace_Pstl_Stroke_LeftCurve: Default
		{
			file=QPATHTOF(Gestures\Pstl\MOCAP_Gesture_CombatPace_Pstl_Stroke_LeftCurve.rtm);
			looped=0;
			speed=1;
			duty=1;
			aimingBody="aimingUpDefault";
			mask="handsPstlStroke";
			leftHandIKBeg=1;
			leftHandIKCurve[]={};
			leftHandIKEnd=0;
			rightHandIKBeg=1;
			rightHandIKCurve[]={};
			rightHandIKEnd=1;
			weaponIK=0;
			enableOptics=0;
			showWeaponAim=0;
			disableWeapons=1;
			disableWeaponsLong=1;
			canPullTrigger=0;
			soundOverride="rifle_to_handgun";
		};
		class MOCAP_Gesture_CombatPace_Lnr_Stroke_DirectCurve: Default
		{
			file=QPATHTOF(Gestures\Lnr\MOCAP_Gesture_CombatPace_Lnr_Stroke_DirectCurve.rtm);
			looped=0;
			speed=0.60000002;
			duty=1;
			aimingBody="aimingUpLauncher";
			mask="handsLnrStroke";
			leftHandIKBeg=1;
			leftHandIKCurve[]={1};
			leftHandIKEnd=1;
			rightHandIKBeg=1;
			rightHandIKCurve[]={1};
			rightHandIKEnd=1;
			weaponIK=4;
			enableOptics=0;
			showWeaponAim=0;
			disableWeapons=1;
			disableWeaponsLong=1;
			canPullTrigger=0;
			soundOverride="rifle_to_handgun";
		};
		class MOCAP_Gesture_CivPace_Non_Idle_Combat_Pose: Default
		{
			file=QPATHTOF(Gestures\Non\Moves\MOCAP_Gesture_CivPace_Non_Idle_Combat_Pose.rtm);
			looped=1;
			speed=0.02;
			duty=1;
			aimingBody="aimingUpDefault";
			mask="handsWeapon";
			leftHandIKBeg=0;
			leftHandIKCurve[]={1};
			leftHandIKEnd=0;
			rightHandIKBeg=0;
			rightHandIKCurve[]={1};
			rightHandIKEnd=0;
			weaponIK=0;
			enableOptics=0;
			showWeaponAim=0;
			disableWeapons=1;
			disableWeaponsLong=1;
			canPullTrigger=0;
			interpolationSpeed=2;
			variantsPlayer[]={};
			variantsAI[]={};
			InterpolateTo[]={};
			interpolateFrom[]={};
			soundOverride="rifle_to_handgun";
			soundEnabled=1;
			showHandGun=0;
			showItemInRightHand=0;
		};
		class MOCAP_Gesture_CivPace_Non_HandsUp_Combat_Pose: Default
		{
			file=QPATHTOF(Gestures\Non\Moves\MOCAP_Gesture_CivPace_Non_HandsUp_Combat_Pose.rtm);
			looped=0;
			speed=0.80000001;
			duty=1;
			aimingBody="aimingUpDefault";
			mask="handsWeapon";
			leftHandIKBeg=0;
			leftHandIKCurve[]={1};
			leftHandIKEnd=0;
			rightHandIKBeg=0;
			rightHandIKCurve[]={1};
			rightHandIKEnd=0;
			weaponIK=0;
			enableOptics=0;
			showWeaponAim=0;
			disableWeapons=1;
			disableWeaponsLong=1;
			canPullTrigger=0;
			variantsPlayer[]={};
			variantsAI[]={};
			soundOverride="rifle_to_handgun";
			soundEnabled=1;
			showHandGun=0;
			showItemInRightHand=0;
		};
		class MOCAP_Gesture_CivPace_Non_HandsDown_Combat_Pose: Default
		{
			file=QPATHTOF(Gestures\Non\Moves\MOCAP_Gesture_CivPace_Non_HandsDown_Combat_Pose.rtm);
			looped=0;
			speed=0.80000001;
			duty=1;
			aimingBody="aimingUpDefault";
			mask="handsWeapon";
			leftHandIKBeg=0;
			leftHandIKCurve[]={1};
			leftHandIKEnd=0;
			rightHandIKBeg=0;
			rightHandIKCurve[]={1};
			rightHandIKEnd=0;
			weaponIK=0;
			enableOptics=0;
			showWeaponAim=0;
			disableWeapons=1;
			disableWeaponsLong=1;
			canPullTrigger=0;
			soundOverride="rifle_to_handgun";
			soundEnabled=1;
			showHandGun=0;
			showItemInRightHand=0;
		};
		class MOCAP_Gesture_CivPace_Non_Punch_Hand_Left_Direct: Default
		{
			file=QPATHTOF(Gestures\Non\MOCAP_Gesture_CivPace_Non_Punch_Hand_Left_Direct.rtm);
			looped=0;
			speed=0.75;
			duty=1;
			aimingBody="aimingUpDefault";
			mask="handsWeapon";
			leftHandIKBeg=0;
			leftHandIKCurve[]={1};
			leftHandIKEnd=0;
			rightHandIKBeg=0;
			rightHandIKCurve[]={1};
			rightHandIKEnd=0;
			weaponIK=0;
			enableOptics=0;
			showWeaponAim=0;
			disableWeapons=1;
			disableWeaponsLong=1;
			canPullTrigger=0;
			InterpolateTo[]={};
			interpolateFrom[]={};
			soundOverride="rifle_to_handgun";
		};
		class MOCAP_Gesture_CivPace_Non_Punch_Hand_Right_Direct: Default
		{
			file=QPATHTOF(Gestures\Non\MOCAP_Gesture_CivPace_Non_Punch_Hand_Right_Direct.rtm);
			looped=0;
			speed=0.69999999;
			duty=1;
			aimingBody="aimingUpDefault";
			mask="handsWeapon";
			leftHandIKBeg=0;
			leftHandIKCurve[]={1};
			leftHandIKEnd=0;
			rightHandIKBeg=0;
			rightHandIKCurve[]={1};
			rightHandIKEnd=0;
			weaponIK=0;
			enableOptics=0;
			showWeaponAim=0;
			disableWeapons=1;
			disableWeaponsLong=1;
			canPullTrigger=0;
			soundOverride="rifle_to_handgun";
		};
		class MOCAP_Weap_m9b_Reload: Default
		{
			file=QPATHTOF(Gestures\Knf\MOCAP_Gesture_NonPace_Knf_Reload_Holder.rtm);
			looped=0;
			speed=0.40000001;
			mask="handsWeapon_pst";
			headBobStrength=0.2;
			headBobMode=2;
			rightHandIKBeg=1;
			rightHandIKEnd=1;
			leftHandIKCurve[]={0,1,0.050000001,0,0.94999999,0,1,1};
		};
	};
	class BlendAnims
	{
		handsRflStroke[]=
		{
			"head",
			0,
			"neck1",
			0,
			"neck",
			0,
			"weapon",
			1,
			"LeftShoulder",
			1,
			"LeftArm",
			1,
			"LeftArmRoll",
			1,
			"LeftForeArm",
			1,
			"LeftForeArmRoll",
			1,
			"LeftHand",
			1,
			"LeftHandRing",
			1,
			"LeftHandPinky1",
			1,
			"LeftHandPinky2",
			1,
			"LeftHandPinky3",
			1,
			"LeftHandRing1",
			1,
			"LeftHandRing2",
			1,
			"LeftHandRing3",
			1,
			"LeftHandMiddle1",
			1,
			"LeftHandMiddle2",
			1,
			"LeftHandMiddle3",
			1,
			"LeftHandIndex1",
			1,
			"LeftHandIndex2",
			1,
			"LeftHandIndex3",
			1,
			"LeftHandThumb1",
			1,
			"LeftHandThumb2",
			1,
			"LeftHandThumb3",
			1,
			"RightShoulder",
			1,
			"RightArm",
			1,
			"RightArmRoll",
			1,
			"RightForeArm",
			1,
			"RightForeArmRoll",
			1,
			"RightHand",
			1,
			"RightHandRing",
			1,
			"RightHandPinky1",
			1,
			"RightHandPinky2",
			1,
			"RightHandPinky3",
			1,
			"RightHandRing1",
			1,
			"RightHandRing2",
			1,
			"RightHandRing3",
			1,
			"RightHandMiddle1",
			1,
			"RightHandMiddle2",
			1,
			"RightHandMiddle3",
			1,
			"RightHandIndex1",
			1,
			"RightHandIndex2",
			1,
			"RightHandIndex3",
			1,
			"RightHandThumb1",
			1,
			"RightHandThumb2",
			1,
			"RightHandThumb3",
			1,
			"Spine",
			1,
			"Spine1",
			1,
			"Spine2",
			1,
			"Spine3",
			1,
			"pelvis",
			"MaskStart"
		};
		handsPstlStroke[]=
		{
			"head",
			0,
			"neck1",
			0,
			"neck",
			0,
			"weapon",
			1,
			"LeftShoulder",
			1,
			"LeftArm",
			1,
			"LeftArmRoll",
			1,
			"LeftForeArm",
			1,
			"LeftForeArmRoll",
			1,
			"LeftHand",
			1,
			"LeftHandRing",
			1,
			"LeftHandPinky1",
			1,
			"LeftHandPinky2",
			1,
			"LeftHandPinky3",
			1,
			"LeftHandRing1",
			1,
			"LeftHandRing2",
			1,
			"LeftHandRing3",
			1,
			"LeftHandMiddle1",
			1,
			"LeftHandMiddle2",
			1,
			"LeftHandMiddle3",
			1,
			"LeftHandIndex1",
			1,
			"LeftHandIndex2",
			1,
			"LeftHandIndex3",
			1,
			"LeftHandThumb1",
			1,
			"LeftHandThumb2",
			1,
			"LeftHandThumb3",
			1,
			"RightShoulder",
			1,
			"RightArm",
			1,
			"RightArmRoll",
			1,
			"RightForeArm",
			1,
			"RightForeArmRoll",
			1,
			"RightHand",
			1,
			"RightHandRing",
			1,
			"RightHandPinky1",
			1,
			"RightHandPinky2",
			1,
			"RightHandPinky3",
			1,
			"RightHandRing1",
			1,
			"RightHandRing2",
			1,
			"RightHandRing3",
			1,
			"RightHandMiddle1",
			1,
			"RightHandMiddle2",
			1,
			"RightHandMiddle3",
			1,
			"RightHandIndex1",
			1,
			"RightHandIndex2",
			1,
			"RightHandIndex3",
			1,
			"RightHandThumb1",
			1,
			"RightHandThumb2",
			1,
			"RightHandThumb3",
			1,
			"Spine",
			1,
			"Spine1",
			1,
			"Spine2",
			1,
			"Spine3",
			1,
			"pelvis",
			"MaskStart"
		};
		handsLnrStroke[]=
		{
			"head",
			0,
			"neck1",
			0,
			"neck",
			0,
			"weapon",
			1,
			"launcher",
			1,
			"LeftShoulder",
			1,
			"LeftArm",
			1,
			"LeftArmRoll",
			1,
			"LeftForeArm",
			1,
			"LeftForeArmRoll",
			1,
			"LeftHand",
			1,
			"LeftHandRing",
			1,
			"LeftHandPinky1",
			1,
			"LeftHandPinky2",
			1,
			"LeftHandPinky3",
			1,
			"LeftHandRing1",
			1,
			"LeftHandRing2",
			1,
			"LeftHandRing3",
			1,
			"LeftHandMiddle1",
			1,
			"LeftHandMiddle2",
			1,
			"LeftHandMiddle3",
			1,
			"LeftHandIndex1",
			1,
			"LeftHandIndex2",
			1,
			"LeftHandIndex3",
			1,
			"LeftHandThumb1",
			1,
			"LeftHandThumb2",
			1,
			"LeftHandThumb3",
			1,
			"RightShoulder",
			1,
			"RightArm",
			1,
			"RightArmRoll",
			1,
			"RightForeArm",
			1,
			"RightForeArmRoll",
			1,
			"RightHand",
			1,
			"RightHandRing",
			1,
			"RightHandPinky1",
			1,
			"RightHandPinky2",
			1,
			"RightHandPinky3",
			1,
			"RightHandRing1",
			1,
			"RightHandRing2",
			1,
			"RightHandRing3",
			1,
			"RightHandMiddle1",
			1,
			"RightHandMiddle2",
			1,
			"RightHandMiddle3",
			1,
			"RightHandIndex1",
			1,
			"RightHandIndex2",
			1,
			"RightHandIndex3",
			1,
			"RightHandThumb1",
			1,
			"RightHandThumb2",
			1,
			"RightHandThumb3",
			1,
			"Spine",
			1,
			"Spine1",
			1,
			"Spine2",
			1,
			"Spine3",
			1,
			"pelvis",
			"MaskStart"
		};
		handsNonPounch[]=
		{
			"head",
			0,
			"neck1",
			0,
			"neck",
			0,
			"weapon",
			1,
			"launcher",
			1,
			"LeftShoulder",
			1,
			"LeftArm",
			1,
			"LeftArmRoll",
			1,
			"LeftForeArm",
			1,
			"LeftForeArmRoll",
			1,
			"LeftHand",
			1,
			"LeftHandRing",
			1,
			"LeftHandPinky1",
			1,
			"LeftHandPinky2",
			1,
			"LeftHandPinky3",
			1,
			"LeftHandRing1",
			1,
			"LeftHandRing2",
			1,
			"LeftHandRing3",
			1,
			"LeftHandMiddle1",
			1,
			"LeftHandMiddle2",
			1,
			"LeftHandMiddle3",
			1,
			"LeftHandIndex1",
			1,
			"LeftHandIndex2",
			1,
			"LeftHandIndex3",
			1,
			"LeftHandThumb1",
			1,
			"LeftHandThumb2",
			1,
			"LeftHandThumb3",
			1,
			"RightShoulder",
			1,
			"RightArm",
			1,
			"RightArmRoll",
			1,
			"RightForeArm",
			1,
			"RightForeArmRoll",
			1,
			"RightHand",
			1,
			"RightHandRing",
			1,
			"RightHandPinky1",
			1,
			"RightHandPinky2",
			1,
			"RightHandPinky3",
			1,
			"RightHandRing1",
			1,
			"RightHandRing2",
			1,
			"RightHandRing3",
			1,
			"RightHandMiddle1",
			1,
			"RightHandMiddle2",
			1,
			"RightHandMiddle3",
			1,
			"RightHandIndex1",
			1,
			"RightHandIndex2",
			1,
			"RightHandIndex3",
			1,
			"RightHandThumb1",
			1,
			"RightHandThumb2",
			1,
			"RightHandThumb3",
			1,
			"Spine",
			0.40000001,
			"Spine1",
			0.80000001,
			"Spine2",
			1,
			"Spine3",
			1,
			"pelvis",
			1
		};
		meleeUpperBodySmooth[]=
		{
			"head",
			0,
			"neck1",
			0,
			"neck",
			0,
			"weapon",
			1,
			"launcher",
			1,
			"LeftShoulder",
			1,
			"LeftArm",
			1,
			"LeftArmRoll",
			1,
			"LeftForeArm",
			1,
			"LeftForeArmRoll",
			1,
			"LeftHand",
			1,
			"LeftHandRing",
			1,
			"LeftHandPinky1",
			1,
			"LeftHandPinky2",
			1,
			"LeftHandPinky3",
			1,
			"LeftHandRing1",
			1,
			"LeftHandRing2",
			1,
			"LeftHandRing3",
			1,
			"LeftHandMiddle1",
			1,
			"LeftHandMiddle2",
			1,
			"LeftHandMiddle3",
			1,
			"LeftHandIndex1",
			1,
			"LeftHandIndex2",
			1,
			"LeftHandIndex3",
			1,
			"LeftHandThumb1",
			1,
			"LeftHandThumb2",
			1,
			"LeftHandThumb3",
			1,
			"RightShoulder",
			1,
			"RightArm",
			1,
			"RightArmRoll",
			1,
			"RightForeArm",
			1,
			"RightForeArmRoll",
			1,
			"RightHand",
			1,
			"RightHandRing",
			1,
			"RightHandPinky1",
			1,
			"RightHandPinky2",
			1,
			"RightHandPinky3",
			1,
			"RightHandRing1",
			1,
			"RightHandRing2",
			1,
			"RightHandRing3",
			1,
			"RightHandMiddle1",
			1,
			"RightHandMiddle2",
			1,
			"RightHandMiddle3",
			1,
			"RightHandIndex1",
			1,
			"RightHandIndex2",
			1,
			"RightHandIndex3",
			1,
			"RightHandThumb1",
			1,
			"RightHandThumb2",
			1,
			"RightHandThumb3",
			1,
			"Spine",
			0.2,
			"Spine1",
			0.40000001,
			"Spine2",
			0.60000002,
			"Spine3",
			0.80000001
		};
	};
};
