class CfgMovesBasic
{
	skeletonName="";
	class StandBase;

	class ManActions
	{
		MOCAP_Man_Act_Rfl_Stroke_RightCurve="";
		MOCAP_Man_Act_Rfl_Stroke_DirectCurve="";
		MOCAP_Man_Act_Idle_Stay_CombatPace_Rfl_Push_Kick_LeftLeg="";
		MOCAP_Man_Act_Pstl_Stroke_RightCurve="";
		MOCAP_Man_Act_Pstl_Stroke_LeftCurve="";
		MOCAP_Man_Act_Idle_Stay_CombatPace_Pstl_Push_Kick_LeftLeg="";
		MOCAP_Man_Act_Lnr_Stroke_DirectCurve="";
		MOCAP_Man_Act_Idle_Stay_CombatPace_Lnr_Push_Kick_LeftLeg="";
		MOCAP_Man_Act_Non_CivPace_Non_Punch_Hand_Right_Direct="";
		MOCAP_Man_Act_Non_CivPace_Non_Punch_Hand_Left_Direct="";
		MOCAP_Man_Act_Non_CivPace_Non_Idle_Combat_Pose="";
		MOCAP_Man_Act_Non_CivPace_Non_HandsUp_Combat_Pose="";
		MOCAP_Man_Act_Non_CivPace_Non_HandsDown_Combat_Pose="";
		MOCAP_Man_Act_Idle_Stay_CivPace_Non_Push_Kick_LeftLeg="";
		MOCAP_Weap_m9b_Reload="MOCAP_Weap_m9b_Reload";
		MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Atacker_Grab_Naked_Choke_No_Contr="";
		MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Prey_Grabbed_Naked_Choke_No_Contr="";
		MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Atacker_Grabbed_Legs_Neck_Twist_No_Contr="";
		MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Prey_Grabbed_Legs_Neck_Twist_No_Contr="";
		MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Atacker_Grabbed_OnBack_Naked_Choke_No_Contr="";
		MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Prey_Grabbed_OnBack_Naked_Choke_No_Contr="";
		MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Atacker_Grab_ByLeftLeg_Neck_Twist_No_Contr="";
		MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Prey_Grab_ByLeftLeg_Neck_Twist_No_Contr="";
		MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Atacker_Lying_Neck_Twist_No_Contr="";
		MOCAP_Man_Act_Idle_Prone_CivPace_Un_Prey_Lying_Neck_Twist_No_Contr="";
	};
	class Actions
	{
		class NoActions;
		class RifleBaseStandActions;
		class RifleBaseLowStandActions;
		class RifleKneelActions: RifleBaseStandActions
		{
			MOCAP_Man_Act_Rfl_Stroke_RightCurve[]=
			{
				"MOCAP_Gesture_CombatPace_Rfl_Stroke_RightCurve",
				"Gesture"
			};
			MOCAP_Man_Act_Rfl_Stroke_DirectCurve[]=
			{
				"MOCAP_Gesture_CombatPace_Rfl_Stroke_DirectCurve",
				"Gesture"
			};
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Atacker_Grabbed_Legs_Neck_Twist_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Atacker_Grabbed_Legs_Neck_Twist_No_Contr";
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Atacker_Grabbed_OnBack_Naked_Choke_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Atacker_Grabbed_OnBack_Naked_Choke_No_Contr";
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Prey_Grabbed_OnBack_Naked_Choke_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Prey_Grabbed_OnBack_Naked_Choke_No_Contr";
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Prey_Grab_ByLeftLeg_Neck_Twist_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Prey_Grab_ByLeftLeg_Neck_Twist_No_Contr";
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Atacker_Lying_Neck_Twist_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Atacker_Lying_Neck_Twist_No_Contr";
		};
		class RifleStandActions: RifleBaseStandActions
		{
			MOCAP_Man_Act_Rfl_Stroke_RightCurve[]=
			{
				"MOCAP_Gesture_CombatPace_Rfl_Stroke_RightCurve",
				"Gesture"
			};
			MOCAP_Man_Act_Rfl_Stroke_DirectCurve[]=
			{
				"MOCAP_Gesture_CombatPace_Rfl_Stroke_DirectCurve",
				"Gesture"
			};
			MOCAP_Man_Act_Idle_Stay_CombatPace_Rfl_Push_Kick_LeftLeg="MOCAP_Idle_Stay_CombatPace_Rfl_Push_Kick_LeftLeg";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Atacker_Grab_Naked_Choke_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Atacker_Grab_Naked_Choke_No_Contr";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Prey_Grabbed_Naked_Choke_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Prey_Grabbed_Naked_Choke_No_Contr";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Prey_Grabbed_Legs_Neck_Twist_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Prey_Grabbed_Legs_Neck_Twist_No_Contr";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Atacker_Grab_ByLeftLeg_Neck_Twist_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Atacker_Grab_ByLeftLeg_Neck_Twist_No_Contr";
		};
		class RifleCrouchActions: RifleKneelActions
		{
			MOCAP_Man_Act_Rfl_Stroke_RightCurve[]=
			{
				"MOCAP_Gesture_CombatPace_Rfl_Stroke_RightCurve",
				"Gesture"
			};
			MOCAP_Man_Act_Rfl_Stroke_DirectCurve[]=
			{
				"MOCAP_Gesture_CombatPace_Rfl_Stroke_DirectCurve",
				"Gesture"
			};
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Atacker_Grabbed_Legs_Neck_Twist_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Atacker_Grabbed_Legs_Neck_Twist_No_Contr";
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Atacker_Grabbed_OnBack_Naked_Choke_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Atacker_Grabbed_OnBack_Naked_Choke_No_Contr";
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Prey_Grabbed_OnBack_Naked_Choke_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Prey_Grabbed_OnBack_Naked_Choke_No_Contr";
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Prey_Grab_ByLeftLeg_Neck_Twist_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Prey_Grab_ByLeftLeg_Neck_Twist_No_Contr";
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Atacker_Lying_Neck_Twist_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Atacker_Lying_Neck_Twist_No_Contr";
		};
		class RifleLowStandActions: RifleBaseLowStandActions
		{
			MOCAP_Man_Act_Rfl_Stroke_RightCurve[]=
			{
				"MOCAP_Gesture_CombatPace_Rfl_Stroke_RightCurve",
				"Gesture"
			};
			MOCAP_Man_Act_Rfl_Stroke_DirectCurve[]=
			{
				"MOCAP_Gesture_CombatPace_Rfl_Stroke_DirectCurve",
				"Gesture"
			};
			MOCAP_Man_Act_Idle_Stay_CombatPace_Rfl_Push_Kick_LeftLeg="MOCAP_Idle_Stay_CombatPace_Rfl_Push_Kick_LeftLeg";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Atacker_Grab_Naked_Choke_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Atacker_Grab_Naked_Choke_No_Contr";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Prey_Grabbed_Naked_Choke_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Prey_Grabbed_Naked_Choke_No_Contr";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Prey_Grabbed_Legs_Neck_Twist_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Prey_Grabbed_Legs_Neck_Twist_No_Contr";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Atacker_Grab_ByLeftLeg_Neck_Twist_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Atacker_Grab_ByLeftLeg_Neck_Twist_No_Contr";
		};
		class RifleAdjustStandBaseActions: RifleBaseStandActions
		{
			MOCAP_Man_Act_Rfl_Stroke_RightCurve[]=
			{
				"MOCAP_Gesture_CombatPace_Rfl_Stroke_RightCurve",
				"Gesture"
			};
			MOCAP_Man_Act_Rfl_Stroke_DirectCurve[]=
			{
				"MOCAP_Gesture_CombatPace_Rfl_Stroke_DirectCurve",
				"Gesture"
			};
			MOCAP_Man_Act_Idle_Stay_CombatPace_Rfl_Push_Kick_LeftLeg="MOCAP_Idle_Stay_CombatPace_Rfl_Push_Kick_LeftLeg";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Atacker_Grab_Naked_Choke_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Atacker_Grab_Naked_Choke_No_Contr";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Prey_Grabbed_Naked_Choke_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Prey_Grabbed_Naked_Choke_No_Contr";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Prey_Grabbed_Legs_Neck_Twist_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Prey_Grabbed_Legs_Neck_Twist_No_Contr";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Atacker_Grab_ByLeftLeg_Neck_Twist_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Atacker_Grab_ByLeftLeg_Neck_Twist_No_Contr";
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Prey_Grab_ByLeftLeg_Neck_Twist_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Prey_Grab_ByLeftLeg_Neck_Twist_No_Contr";
		};
		class RifleProneActions: RifleBaseStandActions
		{
			MOCAP_Man_Act_Idle_Prone_CivPace_Un_Prey_Lying_Neck_Twist_No_Contr="MOCAP_Idle_Prone_CivPace_Un_Prey_Lying_Neck_Twist_No_Contr";
		};
		class RifleStandSaluteActions: RifleBaseStandActions
		{
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Atacker_Grab_Naked_Choke_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Atacker_Grab_Naked_Choke_No_Contr";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Prey_Grabbed_Naked_Choke_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Prey_Grabbed_Naked_Choke_No_Contr";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Prey_Grabbed_Legs_Neck_Twist_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Prey_Grabbed_Legs_Neck_Twist_No_Contr";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Atacker_Grab_ByLeftLeg_Neck_Twist_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Atacker_Grab_ByLeftLeg_Neck_Twist_No_Contr";
		};
		class RifleSiTactions: RifleBaseStandActions
		{
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Prey_Grabbed_OnBack_Naked_Choke_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Prey_Grabbed_OnBack_Naked_Choke_No_Contr";
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Prey_Grab_ByLeftLeg_Neck_Twist_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Prey_Grab_ByLeftLeg_Neck_Twist_No_Contr";
		};
		class PistolStandActions: NoActions
		{
			MOCAP_Man_Act_Pstl_Stroke_RightCurve[]=
			{
				"MOCAP_Gesture_CombatPace_Pstl_Stroke_RightCurve",
				"Gesture"
			};
			MOCAP_Man_Act_Pstl_Stroke_LeftCurve[]=
			{
				"MOCAP_Gesture_CombatPace_Pstl_Stroke_LeftCurve",
				"Gesture"
			};
			MOCAP_Man_Act_Idle_Stay_CombatPace_Pstl_Push_Kick_LeftLeg="MOCAP_Idle_Stay_CombatPace_Pstl_Push_Kick_LeftLeg";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Atacker_Grab_Naked_Choke_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Atacker_Grab_Naked_Choke_No_Contr";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Prey_Grabbed_Naked_Choke_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Prey_Grabbed_Naked_Choke_No_Contr";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Prey_Grabbed_Legs_Neck_Twist_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Prey_Grabbed_Legs_Neck_Twist_No_Contr";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Atacker_Grab_ByLeftLeg_Neck_Twist_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Atacker_Grab_ByLeftLeg_Neck_Twist_No_Contr";
		};
		class PistolLowStandActions: PistolStandActions
		{
			MOCAP_Man_Act_Pstl_Stroke_RightCurve[]=
			{
				"MOCAP_Gesture_CombatPace_Pstl_Stroke_RightCurve",
				"Gesture"
			};
			MOCAP_Man_Act_Pstl_Stroke_LeftCurve[]=
			{
				"MOCAP_Gesture_CombatPace_Pstl_Stroke_LeftCurve",
				"Gesture"
			};
			MOCAP_Man_Act_Idle_Stay_CombatPace_Pstl_Push_Kick_LeftLeg="MOCAP_Idle_Stay_CombatPace_Pstl_Push_Kick_LeftLeg";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Atacker_Grab_Naked_Choke_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Atacker_Grab_Naked_Choke_No_Contr";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Prey_Grabbed_Naked_Choke_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Prey_Grabbed_Naked_Choke_No_Contr";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Prey_Grabbed_Legs_Neck_Twist_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Prey_Grabbed_Legs_Neck_Twist_No_Contr";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Atacker_Grab_ByLeftLeg_Neck_Twist_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Atacker_Grab_ByLeftLeg_Neck_Twist_No_Contr";
		};
		class PistolStandActionsNoAdjust: PistolStandActions
		{
			MOCAP_Man_Act_Idle_Stay_CombatPace_Pstl_Push_Kick_LeftLeg="MOCAP_Idle_Stay_CombatPace_Pstl_Push_Kick_LeftLeg";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Atacker_Grab_Naked_Choke_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Atacker_Grab_Naked_Choke_No_Contr";
		};
		class PistolLowStandActionsNoAdjust: PistolLowStandActions
		{
			MOCAP_Man_Act_Idle_Stay_CombatPace_Pstl_Push_Kick_LeftLeg="MOCAP_Idle_Stay_CombatPace_Pstl_Push_Kick_LeftLeg";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Atacker_Grab_Naked_Choke_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Atacker_Grab_Naked_Choke_No_Contr";
		};
		class PistolKneelActions: PistolStandActions
		{
			MOCAP_Man_Act_Pstl_Stroke_RightCurve[]=
			{
				"MOCAP_Gesture_CombatPace_Pstl_Stroke_RightCurve",
				"Gesture"
			};
			MOCAP_Man_Act_Pstl_Stroke_LeftCurve[]=
			{
				"MOCAP_Gesture_CombatPace_Pstl_Stroke_LeftCurve",
				"Gesture"
			};
			MOCAP_Man_Act_Idle_Stay_CombatPace_Pstl_Push_Kick_LeftLeg="";
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Atacker_Grabbed_Legs_Neck_Twist_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Atacker_Grabbed_Legs_Neck_Twist_No_Contr";
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Atacker_Grabbed_OnBack_Naked_Choke_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Atacker_Grabbed_OnBack_Naked_Choke_No_Contr";
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Prey_Grabbed_OnBack_Naked_Choke_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Prey_Grabbed_OnBack_Naked_Choke_No_Contr";
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Prey_Grab_ByLeftLeg_Neck_Twist_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Prey_Grab_ByLeftLeg_Neck_Twist_No_Contr";
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Atacker_Lying_Neck_Twist_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Atacker_Lying_Neck_Twist_No_Contr";
		};
		class PistolLowKneelActions: PistolKneelActions
		{
			MOCAP_Man_Act_Pstl_Stroke_RightCurve[]=
			{
				"MOCAP_Gesture_CombatPace_Pstl_Stroke_RightCurve",
				"Gesture"
			};
			MOCAP_Man_Act_Pstl_Stroke_LeftCurve[]=
			{
				"MOCAP_Gesture_CombatPace_Pstl_Stroke_LeftCurve",
				"Gesture"
			};
			MOCAP_Man_Act_Idle_Stay_CombatPace_Pstl_Push_Kick_LeftLeg="";
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Atacker_Grabbed_Legs_Neck_Twist_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Atacker_Grabbed_Legs_Neck_Twist_No_Contr";
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Atacker_Grabbed_OnBack_Naked_Choke_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Atacker_Grabbed_OnBack_Naked_Choke_No_Contr";
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Prey_Grabbed_OnBack_Naked_Choke_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Prey_Grabbed_OnBack_Naked_Choke_No_Contr";
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Prey_Grab_ByLeftLeg_Neck_Twist_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Prey_Grab_ByLeftLeg_Neck_Twist_No_Contr";
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Atacker_Lying_Neck_Twist_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Atacker_Lying_Neck_Twist_No_Contr";
		};
		class PistolProneActions: PistolStandActions
		{
			MOCAP_Man_Act_Pstl_Stroke_RightCurve="";
			MOCAP_Man_Act_Pstl_Stroke_LeftCurve="";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Pstl_Push_Kick_LeftLeg="";
			MOCAP_Man_Act_Idle_Prone_CivPace_Un_Prey_Lying_Neck_Twist_No_Contr="MOCAP_Idle_Prone_CivPace_Un_Prey_Lying_Neck_Twist_No_Contr";
		};
		class PistolStandSaluteActions: PistolStandActions
		{
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Atacker_Grab_Naked_Choke_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Atacker_Grab_Naked_Choke_No_Contr";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Prey_Grabbed_Naked_Choke_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Prey_Grabbed_Naked_Choke_No_Contr";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Prey_Grabbed_Legs_Neck_Twist_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Prey_Grabbed_Legs_Neck_Twist_No_Contr";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Atacker_Grab_ByLeftLeg_Neck_Twist_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Atacker_Grab_ByLeftLeg_Neck_Twist_No_Contr";
		};
		class PistolSiTactions: PistolStandActions
		{
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Prey_Grabbed_OnBack_Naked_Choke_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Prey_Grabbed_OnBack_Naked_Choke_No_Contr";
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Prey_Grab_ByLeftLeg_Neck_Twist_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Prey_Grab_ByLeftLeg_Neck_Twist_No_Contr";
		};
		class LauncherKneelActions: NoActions
		{
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Atacker_Grabbed_Legs_Neck_Twist_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Atacker_Grabbed_Legs_Neck_Twist_No_Contr";
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Atacker_Grabbed_OnBack_Naked_Choke_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Atacker_Grabbed_OnBack_Naked_Choke_No_Contr";
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Prey_Grabbed_OnBack_Naked_Choke_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Prey_Grabbed_OnBack_Naked_Choke_No_Contr";
			MOCAP_Man_Act_Lnr_Stroke_DirectCurve[]=
			{
				"MOCAP_Gesture_CombatPace_Lnr_Stroke_DirectCurve",
				"Gesture"
			};
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Prey_Grab_ByLeftLeg_Neck_Twist_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Prey_Grab_ByLeftLeg_Neck_Twist_No_Contr";
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Atacker_Lying_Neck_Twist_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Atacker_Lying_Neck_Twist_No_Contr";
		};
		class LauncherStandActions: LauncherKneelActions
		{
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Atacker_Grab_Naked_Choke_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Atacker_Grab_Naked_Choke_No_Contr";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Prey_Grabbed_Naked_Choke_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Prey_Grabbed_Naked_Choke_No_Contr";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Prey_Grabbed_Legs_Neck_Twist_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Prey_Grabbed_Legs_Neck_Twist_No_Contr";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Lnr_Push_Kick_LeftLeg="MOCAP_Idle_Stay_CombatPace_Lnr_Push_Kick_LeftLeg";
			MOCAP_Man_Act_Lnr_Stroke_DirectCurve[]=
			{
				"MOCAP_Gesture_CombatPace_Lnr_Stroke_DirectCurve",
				"Gesture"
			};
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Atacker_Grab_ByLeftLeg_Neck_Twist_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Atacker_Grab_ByLeftLeg_Neck_Twist_No_Contr";
		};
		class LauncherProneActions: LauncherKneelActions
		{
			MOCAP_Man_Act_Lnr_Stroke_DirectCurve="";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Lnr_Push_Kick_LeftLeg="";
			MOCAP_Man_Act_Idle_Prone_CivPace_Un_Prey_Lying_Neck_Twist_No_Contr="MOCAP_Idle_Prone_CivPace_Un_Prey_Lying_Neck_Twist_No_Contr";
		};
		class CivilStandActions: NoActions
		{
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Atacker_Grab_Naked_Choke_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Atacker_Grab_Naked_Choke_No_Contr";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Prey_Grabbed_Naked_Choke_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Prey_Grabbed_Naked_Choke_No_Contr";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Prey_Grabbed_Legs_Neck_Twist_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Prey_Grabbed_Legs_Neck_Twist_No_Contr";
			MOCAP_Man_Act_Non_CivPace_Non_Punch_Hand_Right_Direct[]=
			{
				"MOCAP_Gesture_CivPace_Non_Punch_Hand_Right_Direct",
				"Gesture"
			};
			MOCAP_Man_Act_Non_CivPace_Non_Punch_Hand_Left_Direct[]=
			{
				"MOCAP_Gesture_CivPace_Non_Punch_Hand_Left_Direct",
				"Gesture"
			};
			MOCAP_Man_Act_Non_CivPace_Non_HandsUp_Combat_Pose[]=
			{
				"MOCAP_Gesture_CivPace_Non_HandsUp_Combat_Pose",
				"Gesture"
			};
			MOCAP_Man_Act_Non_CivPace_Non_Idle_Combat_Pose[]=
			{
				"MOCAP_Gesture_CivPace_Non_Idle_Combat_Pose",
				"Gesture"
			};
			MOCAP_Man_Act_Non_CivPace_Non_HandsDown_Combat_Pose[]=
			{
				"MOCAP_Gesture_CivPace_Non_HandsDown_Combat_Pose",
				"Gesture"
			};
			MOCAP_Man_Act_Idle_Stay_CivPace_Non_Push_Kick_LeftLeg="MOCAP_Idle_Stay_CivPace_Non_Push_Kick_LeftLeg";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Atacker_Grab_ByLeftLeg_Neck_Twist_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Atacker_Grab_ByLeftLeg_Neck_Twist_No_Contr";
		};
		class CivilKneelActions: CivilStandActions
		{
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Atacker_Grabbed_Legs_Neck_Twist_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Atacker_Grabbed_Legs_Neck_Twist_No_Contr";
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Atacker_Grabbed_OnBack_Naked_Choke_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Atacker_Grabbed_OnBack_Naked_Choke_No_Contr";
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Prey_Grabbed_OnBack_Naked_Choke_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Prey_Grabbed_OnBack_Naked_Choke_No_Contr";
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Prey_Grab_ByLeftLeg_Neck_Twist_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Prey_Grab_ByLeftLeg_Neck_Twist_No_Contr";
			MOCAP_Man_Act_Non_CivPace_Non_Punch_Hand_Right_Direct[]=
			{
				"MOCAP_Gesture_CivPace_Non_Punch_Hand_Right_Direct",
				"Gesture"
			};
			MOCAP_Man_Act_Non_CivPace_Non_Punch_Hand_Left_Direct[]=
			{
				"MOCAP_Gesture_CivPace_Non_Punch_Hand_Left_Direct",
				"Gesture"
			};
			MOCAP_Man_Act_Non_CivPace_Non_HandsUp_Combat_Pose[]=
			{
				"MOCAP_Gesture_CivPace_Non_HandsUp_Combat_Pose",
				"Gesture"
			};
			MOCAP_Man_Act_Non_CivPace_Non_Idle_Combat_Pose[]=
			{
				"MOCAP_Gesture_CivPace_Non_Idle_Combat_Pose",
				"Gesture"
			};
			MOCAP_Man_Act_Non_CivPace_Non_HandsDown_Combat_Pose[]=
			{
				"MOCAP_Gesture_CivPace_Non_HandsDown_Combat_Pose",
				"Gesture"
			};
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Atacker_Lying_Neck_Twist_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Atacker_Lying_Neck_Twist_No_Contr";
		};
		class CivilProneActions: CivilStandActions
		{
			MOCAP_Man_Act_Non_CivPace_Non_Punch_Hand_Right_Direct="";
			MOCAP_Man_Act_Non_CivPace_Non_Punch_Hand_Left_Direct="";
			MOCAP_Man_Act_Non_CivPace_Non_HandsUp_Combat_Pose="";
			MOCAP_Man_Act_Non_CivPace_Non_Idle_Combat_Pose="";
			MOCAP_Man_Act_Non_CivPace_Non_HandsDown_Combat_Pose="";
			MOCAP_Man_Act_Idle_Prone_CivPace_Un_Prey_Lying_Neck_Twist_No_Contr="MOCAP_Idle_Prone_CivPace_Un_Prey_Lying_Neck_Twist_No_Contr";
		};
		class CivilStandSurrenderActions: CivilStandActions
		{
			MOCAP_Man_Act_Non_CivPace_Non_Punch_Hand_Right_Direct="";
			MOCAP_Man_Act_Non_CivPace_Non_Punch_Hand_Left_Direct="";
			MOCAP_Man_Act_Non_CivPace_Non_HandsUp_Combat_Pose="";
			MOCAP_Man_Act_Non_CivPace_Non_Idle_Combat_Pose="";
			MOCAP_Man_Act_Non_CivPace_Non_HandsDown_Combat_Pose="";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Atacker_Grab_ByLeftLeg_Neck_Twist_No_Contr="";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Prey_Grabbed_Naked_Choke_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Prey_Grabbed_Naked_Choke_No_Contr";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Prey_Grabbed_Legs_Neck_Twist_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Prey_Grabbed_Legs_Neck_Twist_No_Contr";
		};
		class CivilSiTactions: CivilStandActions
		{
			MOCAP_Man_Act_Non_CivPace_Non_Punch_Hand_Right_Direct="";
			MOCAP_Man_Act_Non_CivPace_Non_Punch_Hand_Left_Direct="";
			MOCAP_Man_Act_Non_CivPace_Non_HandsUp_Combat_Pose="";
			MOCAP_Man_Act_Non_CivPace_Non_Idle_Combat_Pose="";
			MOCAP_Man_Act_Non_CivPace_Non_HandsDown_Combat_Pose="";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Atacker_Grab_ByLeftLeg_Neck_Twist_No_Contr="";
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Prey_Grabbed_OnBack_Naked_Choke_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Prey_Grabbed_OnBack_Naked_Choke_No_Contr";
			MOCAP_Man_Act_Idle_Kneel_CombatPace_Un_Prey_Grab_ByLeftLeg_Neck_Twist_No_Contr="MOCAP_Idle_Kneel_CombatPace_Un_Prey_Grab_ByLeftLeg_Neck_Twist_No_Contr";
		};
		class CivilStandSaluteActions: CivilStandActions
		{
			MOCAP_Man_Act_Non_CivPace_Non_Punch_Hand_Right_Direct="";
			MOCAP_Man_Act_Non_CivPace_Non_Punch_Hand_Left_Direct="";
			MOCAP_Man_Act_Non_CivPace_Non_HandsUp_Combat_Pose="";
			MOCAP_Man_Act_Non_CivPace_Non_Idle_Combat_Pose="";
			MOCAP_Man_Act_Non_CivPace_Non_HandsDown_Combat_Pose="";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Atacker_Grab_ByLeftLeg_Neck_Twist_No_Contr="";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Prey_Grabbed_Naked_Choke_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Prey_Grabbed_Naked_Choke_No_Contr";
			MOCAP_Man_Act_Idle_Stay_CombatPace_Un_Prey_Grabbed_Legs_Neck_Twist_No_Contr="MOCAP_Idle_Stay_CombatPace_Un_Prey_Grabbed_Legs_Neck_Twist_No_Contr";
		};
		class CivilEvasiveActions: CivilStandActions
		{
			MOCAP_Man_Act_Non_CivPace_Non_Punch_Hand_Right_Direct[]=
			{
				"MOCAP_Gesture_CivPace_Non_Punch_Hand_Right_Direct",
				"Gesture"
			};
			MOCAP_Man_Act_Non_CivPace_Non_Punch_Hand_Left_Direct[]=
			{
				"MOCAP_Gesture_CivPace_Non_Punch_Hand_Left_Direct",
				"Gesture"
			};
			MOCAP_Man_Act_Non_CivPace_Non_HandsUp_Combat_Pose[]=
			{
				"MOCAP_Gesture_CivPace_Non_HandsUp_Combat_Pose",
				"Gesture"
			};
			MOCAP_Man_Act_Non_CivPace_Non_Idle_Combat_Pose[]=
			{
				"MOCAP_Gesture_CivPace_Non_Idle_Combat_Pose",
				"Gesture"
			};
			MOCAP_Man_Act_Non_CivPace_Non_HandsDown_Combat_Pose[]=
			{
				"MOCAP_Gesture_CivPace_Non_HandsDown_Combat_Pose",
				"Gesture"
			};
		};
		class CivilRunActions: CivilStandActions
		{
			MOCAP_Man_Act_Non_CivPace_Non_Punch_Hand_Right_Direct[]=
			{
				"MOCAP_Gesture_CivPace_Non_Punch_Hand_Right_Direct",
				"Gesture"
			};
			MOCAP_Man_Act_Non_CivPace_Non_Punch_Hand_Left_Direct[]=
			{
				"MOCAP_Gesture_CivPace_Non_Punch_Hand_Left_Direct",
				"Gesture"
			};
			MOCAP_Man_Act_Non_CivPace_Non_HandsUp_Combat_Pose[]=
			{
				"MOCAP_Gesture_CivPace_Non_HandsUp_Combat_Pose",
				"Gesture"
			};
			MOCAP_Man_Act_Non_CivPace_Non_Idle_Combat_Pose[]=
			{
				"MOCAP_Gesture_CivPace_Non_Idle_Combat_Pose",
				"Gesture"
			};
			MOCAP_Man_Act_Non_CivPace_Non_HandsDown_Combat_Pose[]=
			{
				"MOCAP_Gesture_CivPace_Non_HandsDown_Combat_Pose",
				"Gesture"
			};
		};
	};
};
class CfgMovesMaleSdr: CfgMovesBasic
{
	skeletonName="OFP2_ManSkeleton";
	gestures="CfgGesturesMale";
	class States
	{
		class AmovPercMstpSlowWrflDnon;
		class AmovPercMstpSrasWrflDnon;
		class AmovPknlMstpSlowWrflDnon;
		class AmovPknlMstpSrasWrflDnon;
		class AmovPsitMstpSrasWrflDnon;
		class AmovPercMstpSrasWrflDnon_Salute;
		class AmovPercMstpSlowWrflDnon_Salute;
		class AmovPercMstpSlowWpstDnon;
		class AmovPercMstpSrasWpstDnon;
		class AmovPknlMstpSlowWpstDnon;
		class AmovPknlMstpSrasWpstDnon;
		class amovpsitmstpsnonwpstdnon_ground;
		class AmovPercMstpSrasWpstDnon_Salute;
		class AmovPercMstpSnonWnonDnon;
		class AmovPknlMstpSnonWnonDnon;
		class AmovPpneMstpSnonWnonDnon;
		class AmovPsitMstpSnonWnonDnon_ground;
		class amovpercmstpsnonwnondnon_salute;
		class AmovPercMstpSsurWnonDnon;
		class AmovPercMstpSrasWlnrDnon;
		class AmovPercMstpSlowWlnrDnon;
		class AmovPknlMstpSrasWlnrDnon;
		class AmovPercMstpSlowWrflDnon_gear;
		class AovrPercMstpSnonWnonDf;
		class DeadState;
		class Maya_test: AovrPercMstpSnonWnonDf
		{
			file=QPATHTOF(Moves\Maya_test.rtm);
			looped=0;
			speed=0.69999999;
			mask="BodyFull";
			leftHandIKBeg=0;
			leftHandIKCurve[]={};
			leftHandIKEnd=0;
			rightHandIKBeg=0;
			rightHandIKCurve[]={};
			rightHandIKEnd=0;
			weaponIK=0;
			enableOptics=0;
			showWeaponAim=0;
			disableWeapons=0;
			disableWeaponsLong=0;
			leaning="empty";
			aimingBody="empty";
			aiming="empty";
			forceAim=1;
			limitGunMovement=9.1000004;
			headBobMode=0;
			headBobStrength=0;
			canPullTrigger=0;
			enableDirectControl=0;
			weaponLowered=0;
			variantsPlayer[]={};
			variantsAI[]={};
			ConnectFrom[]=
			{
				"AmovPercMstpSrasWrflDnon",
				9.0200005,
				"AmovPercMstpSlowWrflDnon",
				9.0200005,
				"AmovPercMstpSoptWbinDnon",
				9.0200005,
				"AmovPercMstpSnonWnonDnon",
				9.0200005,
				"AmovPercMstpSrasWpstDnon",
				9.0200005,
				"AmovPercMstpSlowWpstDnon",
				9.0200005,
				"AmovPercMstpSrasWlnrDnon",
				9.0200005,
				"AmovPercMstpSlowWlnrDnon",
				9.0200005
			};
			ConnectTo[]=
			{
				"AmovPercMstpSrasWrflDnon",
				9.0200005,
				"AmovPercMstpSlowWrflDnon",
				9.0200005,
				"AmovPercMstpSoptWbinDnon",
				9.0200005,
				"AmovPercMstpSnonWnonDnon",
				9.0200005,
				"AmovPercMstpSrasWpstDnon",
				9.0200005,
				"AmovPercMstpSlowWpstDnon",
				9.0200005,
				"AmovPercMstpSrasWlnrDnon",
				9.0200005,
				"AmovPercMstpSlowWlnrDnon",
				9.0200005
			};
			soundOverride="rifle_to_handgun";
			soundEnabled=1;
			showHandGun=1;
			showItemInRightHand=1;
		};
		class mocap_test_anim_hands: AmovPercMstpSnonWnonDnon
		{
			file="";
			looped=0;
			speed=0.2;
			mask="BodyFull";
			leftHandIKBeg=0;
			leftHandIKCurve[]={};
			leftHandIKEnd=0;
			rightHandIKBeg=0;
			rightHandIKCurve[]={};
			rightHandIKEnd=0;
			weaponIK=0;
			enableOptics=0;
			showWeaponAim=0;
			disableWeapons=0;
			disableWeaponsLong=0;
			leaning="leaningDefault";
			aimingBody="aimingUpDefault";
			aiming="aimingDefault";
			canBlendStep=0;
			forceAim=0;
			limitGunMovement=9.1000004;
			headBobMode=0;
			headBobStrength=0;
			canPullTrigger=0;
			enableDirectControl=0;
			weaponLowered=0;
			variantsPlayer[]={};
			variantsAI[]={};
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				9.0200005
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.02
			};
			soundOverride="rifle_to_handgun";
			soundEnabled=1;
			showHandGun=0;
			showItemInRightHand=0;
		};
		class MOCAP_Idle_Stay_CombatPace_Rfl_Push_Kick_LeftLeg: AmovPercMstpSrasWrflDnon
		{
			file=QPATHTOF(Strikes\MOCAP_Idle_Stay_CombatPace_Rfl_Push_Kick_LeftLeg.rtm);
			looped=0;
			speed=0.69999999;
			duty=0.69999999;
			mask="BodyFull";
			leftHandIKBeg=1;
			leftHandIKCurve[]={1};
			leftHandIKEnd=1;
			rightHandIKBeg=1;
			rightHandIKCurve[]={1};
			rightHandIKEnd=1;
			weaponIK=1;
			enableOptics=0;
			showWeaponAim=0;
			disableWeapons=0;
			disableWeaponsLong=0;
			leaning="empty";
			aimingBody="empty";
			aiming="empty";
			forceAim=1;
			limitGunMovement=9.1000004;
			headBobMode=0;
			headBobStrength=0;
			canPullTrigger=1;
			enableDirectControl=0;
			weaponLowered=0;
			variantsPlayer[]={};
			variantsAI[]={};
			ConnectFrom[]=
			{
				"AmovPercMstpSrasWrflDnon",
				9.0200005,
				"AmovPercMstpSlowWrflDnon",
				9.0200005,
				"aadjpercmstpsraswrflddown_amovpercmstpsraswrfldnon",
				9.0200005,
				"aadjpercmstpsraswrfldup_amovpercmstpsraswrfldnon",
				9.0200005,
				"aadjpercmstpsraswrfldright_amovpercmstpsraswrfldnon",
				9.0200005,
				"aadjpercmstpsraswrfldleft_amovpercmstpsraswrfldnon",
				9.0200005
			};
			ConnectTo[]=
			{
				"AmovPercMstpSrasWrflDnon",
				0.02
			};
			soundOverride="rifle_to_handgun";
			soundEnabled=1;
			showHandGun=0;
			showItemInRightHand=0;
		};
		class MOCAP_Idle_Stay_CombatPace_Pstl_Push_Kick_LeftLeg: AmovPercMstpSrasWpstDnon
		{
			file=QPATHTOF(Strikes\MOCAP_Idle_Stay_CombatPace_Pstl_Push_Kick_LeftLeg.rtm);
			looped=0;
			speed=0.80000001;
			duty=0.69999999;
			mask="BodyFull";
			leftHandIKBeg=1;
			leftHandIKCurve[]={1};
			leftHandIKEnd=1;
			rightHandIKBeg=1;
			rightHandIKCurve[]={1};
			rightHandIKEnd=1;
			weaponIK=0;
			enableOptics=0;
			showWeaponAim=0;
			disableWeapons=0;
			disableWeaponsLong=0;
			leaning="empty";
			aimingBody="empty";
			aiming="empty";
			forceAim=1;
			limitGunMovement=9.1000004;
			headBobMode=0;
			headBobStrength=0;
			canPullTrigger=1;
			enableDirectControl=0;
			weaponLowered=0;
			variantsPlayer[]={};
			variantsAI[]={};
			ConnectFrom[]=
			{
				"AmovPercMstpSrasWpstDnon",
				9.0200005,
				"AmovPercMstpSlowWpstDnon",
				9.0200005,
				"aadjpercmstpsraswpstddown_amovpercmstpsraswpstdnon",
				9.0200005,
				"aadjpercmstpsraswpstdup_amovpercmstpsraswpstdnon",
				9.0200005,
				"aadjpercmstpsraswpstdright_amovpercmstpsraswpstdnon",
				9.0200005,
				"aadjpercmstpsraswpstdleft_amovpercmstpsraswpstdnon",
				9.0200005
			};
			ConnectTo[]=
			{
				"AmovPercMstpSrasWpstDnon",
				0.02
			};
			soundOverride="rifle_to_handgun";
			soundEnabled=1;
		};
		class MOCAP_Idle_Stay_CombatPace_Lnr_Push_Kick_LeftLeg: AmovPercMstpSrasWlnrDnon
		{
			file=QPATHTOF(Strikes\MOCAP_Idle_Stay_CombatPace_Lnr_Push_Kick_LeftLeg.rtm);
			looped=0;
			speed=0.80000001;
			duty=0.69999999;
			mask="BodyFull";
			leftHandIKBeg=1;
			leftHandIKCurve[]={1};
			leftHandIKEnd=1;
			rightHandIKBeg=1;
			rightHandIKCurve[]={1};
			rightHandIKEnd=1;
			weaponIK=4;
			enableOptics=0;
			showWeaponAim=0;
			disableWeapons=0;
			disableWeaponsLong=0;
			leaning="empty";
			aimingBody="empty";
			aiming="empty";
			forceAim=1;
			limitGunMovement=9.1000004;
			headBobMode=0;
			headBobStrength=0;
			canPullTrigger=0;
			enableDirectControl=0;
			weaponLowered=0;
			variantsPlayer[]={};
			variantsAI[]={};
			ConnectFrom[]=
			{
				"AmovPercMstpSrasWlnrDnon",
				9.0200005,
				"AmovPercMstpSlowWlnrDnon",
				9.0200005
			};
			ConnectTo[]=
			{
				"AmovPercMstpSrasWlnrDnon",
				0.02,
				"AmovPercMstpSlowWlnrDnon",
				0.02
			};
			soundOverride="rifle_to_handgun";
			soundEnabled=1;
		};
		class MOCAP_Idle_Stay_CivPace_Non_Push_Kick_LeftLeg: AmovPercMstpSnonWnonDnon
		{
			file=QPATHTOF(Strikes\MOCAP_Idle_Stay_CivPace_Non_Push_Kick_LeftLeg.rtm);
			looped=0;
			speed=0.69999999;
			duty=0.69999999;
			mask="BodyFull";
			leftHandIKBeg=0;
			leftHandIKCurve[]={1};
			leftHandIKEnd=0;
			rightHandIKBeg=0;
			rightHandIKCurve[]={1};
			rightHandIKEnd=0;
			weaponIK=0;
			enableOptics=0;
			showWeaponAim=0;
			disableWeapons=0;
			disableWeaponsLong=0;
			leaning="empty";
			aimingBody="empty";
			aiming="empty";
			forceAim=1;
			limitGunMovement=9.1000004;
			headBobMode=0;
			headBobStrength=0;
			canPullTrigger=0;
			enableDirectControl=0;
			weaponLowered=0;
			variantsPlayer[]={};
			variantsAI[]={};
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				9.0200005
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.02
			};
			soundOverride="rifle_to_handgun";
			soundEnabled=1;
		};
		class MOCAP_Idle_Stay_CombatPace_Un_Atacker_Grab_Naked_Choke_No_Contr: AmovPknlMstpSnonWnonDnon
		{
			file=QPATHTOF(Grabs\MOCAP_Idle_Stay_CombatPace_Un_Atacker_Grab_Naked_Choke_No_Contr.rtm);
			looped=0;
			speed=0.1;
			duty=2;
			mask="BodyFull";
			leftHandIKBeg=1;
			leftHandIKCurve[]={1};
			leftHandIKEnd=1;
			rightHandIKBeg=1;
			rightHandIKCurve[]={1};
			rightHandIKEnd=1;
			weaponIK=0;
			enableOptics=0;
			showWeaponAim=0;
			disableWeapons=1;
			disableWeaponsLong=1;
			leaning="empty";
			aimingBody="empty";
			aiming="empty";
			head="empty";
			forceAim=1;
			limitGunMovement=9.1000004;
			headBobMode=1;
			headBobStrength=0;
			canPullTrigger=0;
			enableDirectControl=0;
			variantsPlayer[]={};
			variantsAI[]={};
			ConnectFrom[]=
			{
				"AmovPercMstpSrasWlnrDnon",
				9.0200005,
				"AmovPercMstpSlowWrflDnon_gear",
				9.0200005,
				"AmovPercMstpSoptWbinDnon",
				9.0200005,
				"AidlPercMstpSnonWnonDnon_AI",
				9.0200005,
				"aidlpercmstpslowwrfldnon_ai",
				9.0200005,
				"aidlpercmstpsraswrfldnon_ai",
				9.0200005,
				"AidlPercMstpSrasWpstDnon_AI",
				9.0200005,
				"AidlPercMstpSlowWpstDnon_AI",
				9.0200005,
				"AidlPercMstpSrasWlnrDnon_AI",
				9.0200005,
				"AmovPercMstpSnonWnonDnon",
				9.0200005,
				"AmovPercMstpSrasWrflDnon",
				9.0200005,
				"AmovPercMstpSlowWrflDnon",
				9.0200005,
				"AmovPercMstpSlowWpstDnon",
				9.0200005,
				"AmovPercMstpSrasWpstDnon",
				9.0200005,
				"aadjpercmstpsraswrflddown_amovpercmstpsraswrfldnon",
				9.0200005,
				"aadjpercmstpsraswrfldup_amovpercmstpsraswrfldnon",
				9.0200005,
				"aadjpercmstpsraswrfldright_amovpercmstpsraswrfldnon",
				9.0200005,
				"aadjpercmstpsraswrfldleft_amovpercmstpsraswrfldnon",
				9.0200005
			};
			ConnectTo[]=
			{
				"AmovPknlMstpSoptWbinDnon",
				0.02,
				"AmovPknlMstpSnonWnonDnon",
				0.02,
				"AmovPknlMstpSrasWrflDnon",
				0.02,
				"AmovPknlMstpSlowWrflDnon",
				0.02,
				"AmovPknlMstpSlowWpstDnon",
				0.02,
				"AmovPknlMstpSrasWpstDnon",
				0.02,
				"AmovPknlMstpSrasWlnrDnon",
				0.02
			};
			showHandGun=0;
			showItemInRightHand=0;
		};
		class MOCAP_Idle_Stay_CombatPace_Un_Prey_Grabbed_Naked_Choke_No_Contr: AmovPercMstpSnonWnonDnon
		{
			file=QPATHTOF(Grabs\MOCAP_Idle_Stay_CombatPace_Un_Prey_Grabbed_Naked_Choke_No_Contr.rtm);
			looped=0;
			speed=0.1;
			duty=2;
			mask="BodyFull";
			leftHandIKBeg=1;
			leftHandIKCurve[]={};
			leftHandIKEnd=1;
			rightHandIKBeg=1;
			rightHandIKCurve[]={};
			rightHandIKEnd=1;
			weaponIK=1;
			enableOptics=0;
			showWeaponAim=0;
			disableWeapons=1;
			disableWeaponsLong=1;
			leaning="empty";
			aimingBody="empty";
			aiming="empty";
			head="empty";
			forceAim=1;
			limitGunMovement=9.1000004;
			headBobMode=0;
			headBobStrength=0;
			canPullTrigger=1;
			enableDirectControl=0;
			variantsPlayer[]={};
			variantsAI[]={};
			ConnectFrom[]=
			{
				"AmovPercMstpSrasWlnrDnon",
				9.0200005,
				"AmovPercMstpSlowWrflDnon_gear",
				9.0200005,
				"AmovPercMstpSoptWbinDnon",
				9.0200005,
				"AidlPercMstpSnonWnonDnon_AI",
				9.0200005,
				"aidlpercmstpslowwrfldnon_ai",
				9.0200005,
				"aidlpercmstpsraswrfldnon_ai",
				9.0200005,
				"AidlPercMstpSrasWpstDnon_AI",
				9.0200005,
				"AidlPercMstpSlowWpstDnon_AI",
				9.0200005,
				"AidlPercMstpSrasWlnrDnon_AI",
				9.0200005,
				"AmovPercMstpSnonWnonDnon",
				9.0200005,
				"AmovPercMstpSrasWrflDnon",
				9.0200005,
				"AmovPercMstpSlowWrflDnon",
				9.0200005,
				"AmovPercMstpSlowWpstDnon",
				9.0200005,
				"AmovPercMstpSrasWpstDnon",
				9.0200005,
				"aadjpercmstpsraswrflddown_amovpercmstpsraswrfldnon",
				9.0200005,
				"aadjpercmstpsraswrfldup_amovpercmstpsraswrfldnon",
				9.0200005,
				"aadjpercmstpsraswrfldright_amovpercmstpsraswrfldnon",
				9.0200005,
				"aadjpercmstpsraswrfldleft_amovpercmstpsraswrfldnon",
				9.0200005,
				"AmovPercMstpSrasWrflDnon_Salute",
				9.0200005,
				"AmovPercMstpSlowWrflDnon_Salute",
				9.0200005,
				"AmovPercMstpSrasWpstDnon_Salute",
				9.0200005,
				"amovpercmstpsnonwnondnon_salute",
				9.0200005,
				"AmovPercMstpSsurWnonDnon",
				9.0200005
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.02,
				"AmovPercMstpSrasWrflDnon",
				0.02,
				"AmovPercMstpSlowWrflDnon",
				0.02,
				"AmovPercMstpSlowWpstDnon",
				0.02,
				"AmovPercMstpSrasWpstDnon",
				0.02,
				"AmovPercMstpSrasWlnrDnon",
				0.02
			};
			showHandGun=0;
			showItemInRightHand=0;
		};
		class MOCAP_Idle_Kneel_CombatPace_Un_Atacker_Grabbed_Legs_Neck_Twist_No_Contr: AmovPknlMstpSnonWnonDnon
		{
			file=QPATHTOF(Grabs\MOCAP_Idle_Kneel_CombatPace_Un_Atacker_Grabbed_Legs_Neck_Twist_No_Contr.rtm);
			looped=0;
			speed=0.17;
			duty=2;
			mask="BodyFull";
			leftHandIKBeg=1;
			leftHandIKCurve[]={1};
			leftHandIKEnd=1;
			rightHandIKBeg=1;
			rightHandIKCurve[]={1};
			rightHandIKEnd=1;
			weaponIK=0;
			enableOptics=0;
			showWeaponAim=0;
			disableWeapons=1;
			disableWeaponsLong=1;
			leaning="empty";
			aimingBody="empty";
			aiming="empty";
			head="empty";
			forceAim=1;
			limitGunMovement=9.1000004;
			headBobMode=1;
			headBobStrength=0;
			canPullTrigger=0;
			enableDirectControl=0;
			variantsPlayer[]={};
			variantsAI[]={};
			ConnectFrom[]=
			{
				"AmovPknlMstpSlowWrflDnon_gear",
				9.0200005,
				"AmovPknlMstpSoptWbinDnon",
				9.0200005,
				"AidlPknlMstpSnonWnonDnon_AI",
				9.0200005,
				"aidlpknlmstpslowwrfldnon_ai",
				9.0200005,
				"aidlpknlmstpsraswrfldnon_ai",
				9.0200005,
				"AidlPknlMstpSlowWpstDnon_AI",
				9.0200005,
				"AidlPknlMstpSrasWpstDnon_AI",
				9.0200005,
				"AidlPknlMstpSrasWlnrDnon_AI",
				9.0200005,
				"AmovPknlMstpSnonWnonDnon",
				9.0200005,
				"AmovPknlMstpSrasWrflDnon",
				9.0200005,
				"AmovPknlMstpSlowWrflDnon",
				9.0200005,
				"AmovPknlMstpSlowWpstDnon",
				9.0200005,
				"AmovPknlMstpSrasWpstDnon",
				9.0200005,
				"AmovPknlMstpSrasWlnrDnon",
				9.0200005,
				"aadjpknlmstpsraswrflddown_amovpknlmstpsraswrfldnon",
				0.02,
				"aadjpknlmstpsraswrfldup_amovpknlmstpsraswrfldnon",
				0.02,
				"aadjpknlmstpsraswrfldright_amovpknlmstpsraswrfldnon",
				0.02,
				"aadjpknlmstpsraswrfldleft_amovpknlmstpsraswrfldnon",
				0.02
			};
			ConnectTo[]=
			{
				"AmovPknlMstpSoptWbinDnon",
				0.02,
				"AmovPknlMstpSnonWnonDnon",
				0.02,
				"AmovPknlMstpSrasWrflDnon",
				0.02,
				"AmovPknlMstpSlowWrflDnon",
				0.02,
				"AmovPknlMstpSlowWpstDnon",
				0.02,
				"AmovPknlMstpSrasWpstDnon",
				0.02,
				"AmovPknlMstpSrasWlnrDnon",
				0.02
			};
			showHandGun=0;
			showItemInRightHand=0;
			soundEnabled=1;
			soundEdge[]={0.1};
			soundOverride="MOCAP_Idle_Kneel_CombatPace_Un_Atacker_Grabbed_Legs_Neck_Twist_No_Contr";
		};
		class MOCAP_Idle_Stay_CombatPace_Un_Prey_Grabbed_Legs_Neck_Twist_No_Contr: AmovPercMstpSnonWnonDnon
		{
			file=QPATHTOF(Grabs\MOCAP_Idle_Stay_CombatPace_Un_Prey_Grabbed_Legs_Neck_Twist_No_Contr.rtm);
			looped=0;
			speed=0.17;
			duty=2;
			mask="BodyFull";
			leftHandIKBeg=1;
			leftHandIKCurve[]={1};
			leftHandIKEnd=1;
			rightHandIKBeg=1;
			rightHandIKCurve[]={1};
			rightHandIKEnd=1;
			weaponIK=0;
			enableOptics=0;
			showWeaponAim=0;
			disableWeapons=1;
			disableWeaponsLong=1;
			leaning="empty";
			aimingBody="empty";
			aiming="empty";
			head="empty";
			forceAim=1;
			limitGunMovement=9.1000004;
			headBobMode=1;
			headBobStrength=0;
			canPullTrigger=0;
			enableDirectControl=0;
			variantsPlayer[]={};
			variantsAI[]={};
			ConnectFrom[]=
			{
				"AmovPercMstpSrasWlnrDnon",
				9.0200005,
				"AmovPercMstpSlowWrflDnon_gear",
				9.0200005,
				"AmovPercMstpSoptWbinDnon",
				9.0200005,
				"AidlPercMstpSnonWnonDnon_AI",
				9.0200005,
				"aidlpercmstpslowwrfldnon_ai",
				9.0200005,
				"aidlpercmstpsraswrfldnon_ai",
				9.0200005,
				"AidlPercMstpSrasWpstDnon_AI",
				9.0200005,
				"AidlPercMstpSlowWpstDnon_AI",
				9.0200005,
				"AidlPercMstpSrasWlnrDnon_AI",
				9.0200005,
				"AmovPercMstpSnonWnonDnon",
				9.0200005,
				"AmovPercMstpSrasWrflDnon",
				9.0200005,
				"AmovPercMstpSlowWrflDnon",
				9.0200005,
				"AmovPercMstpSlowWpstDnon",
				9.0200005,
				"AmovPercMstpSrasWpstDnon",
				9.0200005,
				"aadjpercmstpsraswrflddown_amovpercmstpsraswrfldnon",
				9.0200005,
				"aadjpercmstpsraswrfldup_amovpercmstpsraswrfldnon",
				9.0200005,
				"aadjpercmstpsraswrfldright_amovpercmstpsraswrfldnon",
				9.0200005,
				"aadjpercmstpsraswrfldleft_amovpercmstpsraswrfldnon",
				9.0200005,
				"AmovPercMstpSrasWrflDnon_Salute",
				9.0200005,
				"AmovPercMstpSlowWrflDnon_Salute",
				9.0200005,
				"AmovPercMstpSrasWpstDnon_Salute",
				9.0200005,
				"amovpercmstpsnonwnondnon_salute",
				9.0200005,
				"AmovPercMstpSsurWnonDnon",
				9.0200005
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.02,
				"AmovPercMstpSrasWrflDnon",
				0.02,
				"AmovPercMstpSlowWrflDnon",
				0.02,
				"AmovPercMstpSlowWpstDnon",
				0.02,
				"AmovPercMstpSrasWpstDnon",
				0.02,
				"AmovPercMstpSrasWlnrDnon",
				0.02
			};
			showHandGun=0;
			showItemInRightHand=0;
			soundEnabled=1;
			soundEdge[]={0.1};
		};
		class MOCAP_Idle_Kneel_CombatPace_Un_Atacker_Grabbed_OnBack_Naked_Choke_No_Contr: AmovPknlMstpSnonWnonDnon
		{
			file=QPATHTOF(Grabs\MOCAP_Idle_Kneel_CombatPace_Un_Atacker_Grabbed_OnBack_Naked_Choke_No_Contr.rtm);
			looped=0;
			speed=0.075000003;
			duty=2;
			mask="BodyFull";
			leftHandIKBeg=1;
			leftHandIKCurve[]={1};
			leftHandIKEnd=1;
			rightHandIKBeg=1;
			rightHandIKCurve[]={1};
			rightHandIKEnd=1;
			weaponIK=0;
			enableOptics=0;
			showWeaponAim=0;
			disableWeapons=1;
			disableWeaponsLong=1;
			leaning="empty";
			aimingBody="empty";
			aiming="empty";
			head="empty";
			forceAim=1;
			limitGunMovement=9.1000004;
			headBobMode=1;
			headBobStrength=0;
			canPullTrigger=0;
			enableDirectControl=0;
			variantsPlayer[]={};
			variantsAI[]={};
			ConnectFrom[]=
			{
				"AmovPknlMstpSlowWrflDnon_gear",
				9.0200005,
				"AmovPknlMstpSoptWbinDnon",
				9.0200005,
				"AidlPknlMstpSnonWnonDnon_AI",
				9.0200005,
				"aidlpknlmstpslowwrfldnon_ai",
				9.0200005,
				"aidlpknlmstpsraswrfldnon_ai",
				9.0200005,
				"AidlPknlMstpSlowWpstDnon_AI",
				9.0200005,
				"AidlPknlMstpSrasWpstDnon_AI",
				9.0200005,
				"AidlPknlMstpSrasWlnrDnon_AI",
				9.0200005,
				"AmovPknlMstpSnonWnonDnon",
				9.0200005,
				"AmovPknlMstpSrasWrflDnon",
				9.0200005,
				"AmovPknlMstpSlowWrflDnon",
				9.0200005,
				"AmovPknlMstpSlowWpstDnon",
				9.0200005,
				"AmovPknlMstpSrasWpstDnon",
				9.0200005,
				"AmovPknlMstpSrasWlnrDnon",
				9.0200005,
				"aadjpknlmstpsraswrflddown_amovpknlmstpsraswrfldnon",
				0.02,
				"aadjpknlmstpsraswrfldup_amovpknlmstpsraswrfldnon",
				0.02,
				"aadjpknlmstpsraswrfldright_amovpknlmstpsraswrfldnon",
				0.02,
				"aadjpknlmstpsraswrfldleft_amovpknlmstpsraswrfldnon",
				0.02
			};
			ConnectTo[]=
			{
				"AmovPknlMstpSoptWbinDnon",
				0.02,
				"AmovPknlMstpSnonWnonDnon",
				0.02,
				"AmovPknlMstpSrasWrflDnon",
				0.02,
				"AmovPknlMstpSlowWrflDnon",
				0.02,
				"AmovPknlMstpSlowWpstDnon",
				0.02,
				"AmovPknlMstpSrasWpstDnon",
				0.02,
				"AmovPknlMstpSrasWlnrDnon",
				0.02
			};
			showHandGun=0;
			showItemInRightHand=0;
		};
		class MOCAP_Idle_Kneel_CombatPace_Un_Prey_Grabbed_OnBack_Naked_Choke_No_Contr: AmovPknlMstpSnonWnonDnon
		{
			file=QPATHTOF(Grabs\MOCAP_Idle_Kneel_CombatPace_Un_Prey_Grabbed_OnBack_Naked_Choke_No_Contr.rtm);
			looped=0;
			speed=0.075000003;
			duty=2;
			mask="BodyFull";
			leftHandIKBeg=1;
			leftHandIKCurve[]={1};
			leftHandIKEnd=1;
			rightHandIKBeg=1;
			rightHandIKCurve[]={1};
			rightHandIKEnd=1;
			weaponIK=0;
			enableOptics=0;
			showWeaponAim=0;
			disableWeapons=1;
			disableWeaponsLong=1;
			leaning="empty";
			aimingBody="empty";
			aiming="empty";
			head="empty";
			forceAim=1;
			limitGunMovement=9.1000004;
			headBobMode=1;
			headBobStrength=0;
			canPullTrigger=0;
			enableDirectControl=0;
			variantsPlayer[]={};
			variantsAI[]={};
			ConnectFrom[]=
			{
				"AmovPknlMstpSlowWrflDnon_gear",
				9.0200005,
				"AmovPknlMstpSoptWbinDnon",
				9.0200005,
				"AidlPknlMstpSnonWnonDnon_AI",
				9.0200005,
				"aidlpknlmstpslowwrfldnon_ai",
				9.0200005,
				"aidlpknlmstpsraswrfldnon_ai",
				9.0200005,
				"AidlPknlMstpSlowWpstDnon_AI",
				9.0200005,
				"AidlPknlMstpSrasWpstDnon_AI",
				9.0200005,
				"AidlPknlMstpSrasWlnrDnon_AI",
				9.0200005,
				"AmovPknlMstpSnonWnonDnon",
				9.0200005,
				"AmovPknlMstpSrasWrflDnon",
				9.0200005,
				"AmovPknlMstpSlowWrflDnon",
				9.0200005,
				"AmovPknlMstpSlowWpstDnon",
				9.0200005,
				"AmovPknlMstpSrasWpstDnon",
				9.0200005,
				"AmovPknlMstpSrasWlnrDnon",
				9.0200005,
				"aadjpknlmstpsraswrflddown_amovpknlmstpsraswrfldnon",
				0.02,
				"aadjpknlmstpsraswrfldup_amovpknlmstpsraswrfldnon",
				0.02,
				"aadjpknlmstpsraswrfldright_amovpknlmstpsraswrfldnon",
				0.02,
				"aadjpknlmstpsraswrfldleft_amovpknlmstpsraswrfldnon",
				0.02,
				"AmovPsitMstpSrasWrflDnon",
				9.0200005,
				"amovpsitmstpsnonwpstdnon_ground",
				9.0200005,
				"AmovPsitMstpSnonWnonDnon_ground",
				9.0200005
			};
			ConnectTo[]=
			{
				"AmovPknlMstpSoptWbinDnon",
				0.02,
				"AmovPknlMstpSnonWnonDnon",
				0.02,
				"AmovPknlMstpSrasWrflDnon",
				0.02,
				"AmovPknlMstpSlowWrflDnon",
				0.02,
				"AmovPknlMstpSlowWpstDnon",
				0.02,
				"AmovPknlMstpSrasWpstDnon",
				0.02,
				"AmovPknlMstpSrasWlnrDnon",
				0.02
			};
			showHandGun=0;
			showItemInRightHand=0;
		};
		class MOCAP_Idle_Stay_CombatPace_Un_Atacker_Grab_ByLeftLeg_Neck_Twist_No_Contr: AmovPknlMstpSnonWnonDnon
		{
			file=QPATHTOF(Grabs\MOCAP_Idle_Stay_CombatPace_Un_Atacker_Grab_ByLeftLeg_Neck_Twist_No_Contr.rtm);
			looped=0;
			speed=0.19499999;
			duty=2;
			mask="BodyFull";
			leftHandIKBeg=0;
			leftHandIKCurve[]={};
			leftHandIKEnd=0;
			rightHandIKBeg=0;
			rightHandIKCurve[]={};
			rightHandIKEnd=0;
			weaponIK=0;
			enableOptics=0;
			showWeaponAim=0;
			disableWeapons=1;
			disableWeaponsLong=1;
			leaning="empty";
			aimingBody="empty";
			aiming="empty";
			head="empty";
			forceAim=1;
			limitGunMovement=9.1000004;
			headBobMode=1;
			headBobStrength=0;
			canPullTrigger=0;
			enableDirectControl=0;
			variantsPlayer[]={};
			variantsAI[]={};
			ConnectFrom[]=
			{
				"AmovPercMstpSrasWlnrDnon",
				9.0200005,
				"AmovPercMstpSlowWrflDnon_gear",
				9.0200005,
				"AmovPercMstpSoptWbinDnon",
				9.0200005,
				"AidlPercMstpSnonWnonDnon_AI",
				9.0200005,
				"aidlpercmstpslowwrfldnon_ai",
				9.0200005,
				"aidlpercmstpsraswrfldnon_ai",
				9.0200005,
				"AidlPercMstpSrasWpstDnon_AI",
				9.0200005,
				"AidlPercMstpSlowWpstDnon_AI",
				9.0200005,
				"AidlPercMstpSrasWlnrDnon_AI",
				9.0200005,
				"AmovPercMstpSnonWnonDnon",
				9.0200005,
				"AmovPercMstpSrasWrflDnon",
				9.0200005,
				"AmovPercMstpSlowWrflDnon",
				9.0200005,
				"AmovPercMstpSlowWpstDnon",
				9.0200005,
				"AmovPercMstpSrasWpstDnon",
				9.0200005,
				"aadjpercmstpsraswrflddown_amovpercmstpsraswrfldnon",
				9.0200005,
				"aadjpercmstpsraswrfldup_amovpercmstpsraswrfldnon",
				9.0200005,
				"aadjpercmstpsraswrfldright_amovpercmstpsraswrfldnon",
				9.0200005,
				"aadjpercmstpsraswrfldleft_amovpercmstpsraswrfldnon",
				9.0200005
			};
			ConnectTo[]=
			{
				"AmovPknlMstpSoptWbinDnon",
				0.02,
				"AmovPknlMstpSnonWnonDnon",
				0.02,
				"AmovPknlMstpSrasWrflDnon",
				0.02,
				"AmovPknlMstpSlowWrflDnon",
				0.02,
				"AmovPknlMstpSlowWpstDnon",
				0.02,
				"AmovPknlMstpSrasWpstDnon",
				0.02,
				"AmovPknlMstpSrasWlnrDnon",
				0.02
			};
			showHandGun=0;
			showItemInRightHand=0;
			soundEnabled=1;
			soundEdge[]={0.1};
		};
		class MOCAP_Idle_Kneel_CombatPace_Un_Prey_Grab_ByLeftLeg_Neck_Twist_No_Contr: AmovPknlMstpSnonWnonDnon
		{
			file=QPATHTOF(Grabs\MOCAP_Idle_Kneel_CombatPace_Un_Prey_Grab_ByLeftLeg_Neck_Twist_No_Contr.rtm);
			looped=0;
			speed=0.19499999;
			duty=2;
			mask="BodyFull";
			leftHandIKBeg=0;
			leftHandIKCurve[]={};
			leftHandIKEnd=0;
			rightHandIKBeg=0;
			rightHandIKCurve[]={};
			rightHandIKEnd=0;
			weaponIK=0;
			enableOptics=0;
			showWeaponAim=0;
			disableWeapons=1;
			disableWeaponsLong=1;
			leaning="empty";
			aimingBody="empty";
			aiming="empty";
			head="empty";
			forceAim=1;
			limitGunMovement=9.1000004;
			headBobMode=1;
			headBobStrength=0;
			canPullTrigger=0;
			enableDirectControl=0;
			variantsPlayer[]={};
			variantsAI[]={};
			ConnectFrom[]=
			{
				"AmovPknlMstpSlowWrflDnon_gear",
				9.0200005,
				"AmovPknlMstpSoptWbinDnon",
				9.0200005,
				"AidlPknlMstpSnonWnonDnon_AI",
				9.0200005,
				"aidlpknlmstpslowwrfldnon_ai",
				9.0200005,
				"aidlpknlmstpsraswrfldnon_ai",
				9.0200005,
				"AidlPknlMstpSlowWpstDnon_AI",
				9.0200005,
				"AidlPknlMstpSrasWpstDnon_AI",
				9.0200005,
				"AidlPknlMstpSrasWlnrDnon_AI",
				9.0200005,
				"AmovPknlMstpSnonWnonDnon",
				9.0200005,
				"AmovPknlMstpSrasWrflDnon",
				9.0200005,
				"AmovPknlMstpSlowWrflDnon",
				9.0200005,
				"AmovPknlMstpSlowWpstDnon",
				9.0200005,
				"AmovPknlMstpSrasWpstDnon",
				9.0200005,
				"AmovPknlMstpSrasWlnrDnon",
				9.0200005,
				"aadjpknlmstpsraswrflddown_amovpknlmstpsraswrfldnon",
				0.02,
				"aadjpknlmstpsraswrfldup_amovpknlmstpsraswrfldnon",
				0.02,
				"aadjpknlmstpsraswrfldright_amovpknlmstpsraswrfldnon",
				0.02,
				"aadjpknlmstpsraswrfldleft_amovpknlmstpsraswrfldnon",
				0.02,
				"AmovPsitMstpSrasWrflDnon",
				9.0200005,
				"amovpsitmstpsnonwpstdnon_ground",
				9.0200005,
				"AmovPsitMstpSnonWnonDnon_ground",
				9.0200005
			};
			ConnectTo[]=
			{
				"AmovPknlMstpSoptWbinDnon",
				0.02,
				"AmovPknlMstpSnonWnonDnon",
				0.02,
				"AmovPknlMstpSrasWrflDnon",
				0.02,
				"AmovPknlMstpSlowWrflDnon",
				0.02,
				"AmovPknlMstpSlowWpstDnon",
				0.02,
				"AmovPknlMstpSrasWpstDnon",
				0.02,
				"AmovPknlMstpSrasWlnrDnon",
				0.02
			};
			showHandGun=0;
			showItemInRightHand=0;
		};
		class MOCAP_Idle_Kneel_CombatPace_Un_Atacker_Lying_Neck_Twist_No_Contr: AmovPknlMstpSnonWnonDnon
		{
			file=QPATHTOF(Grabs\MOCAP_Idle_Kneel_CombatPace_Un_Atacker_Lying_Neck_Twist_No_Contr.rtm);
			looped=0;
			speed=0.25;
			duty=2;
			mask="BodyFull";
			leftHandIKBeg=0;
			leftHandIKCurve[]={};
			leftHandIKEnd=0;
			rightHandIKBeg=0;
			rightHandIKCurve[]={};
			rightHandIKEnd=0;
			weaponIK=0;
			enableOptics=0;
			showWeaponAim=0;
			disableWeapons=1;
			disableWeaponsLong=1;
			leaning="empty";
			aimingBody="empty";
			aiming="empty";
			head="empty";
			forceAim=1;
			limitGunMovement=9.1000004;
			headBobMode=1;
			headBobStrength=0;
			canPullTrigger=0;
			enableDirectControl=0;
			variantsPlayer[]={};
			variantsAI[]={};
			ConnectFrom[]=
			{
				"AmovPknlMstpSlowWrflDnon_gear",
				9.0200005,
				"AmovPknlMstpSoptWbinDnon",
				9.0200005,
				"AidlPknlMstpSnonWnonDnon_AI",
				9.0200005,
				"aidlpknlmstpslowwrfldnon_ai",
				9.0200005,
				"aidlpknlmstpsraswrfldnon_ai",
				9.0200005,
				"AidlPknlMstpSlowWpstDnon_AI",
				9.0200005,
				"AidlPknlMstpSrasWpstDnon_AI",
				9.0200005,
				"AidlPknlMstpSrasWlnrDnon_AI",
				9.0200005,
				"AmovPknlMstpSnonWnonDnon",
				9.0200005,
				"AmovPknlMstpSrasWrflDnon",
				9.0200005,
				"AmovPknlMstpSlowWrflDnon",
				9.0200005,
				"AmovPknlMstpSlowWpstDnon",
				9.0200005,
				"AmovPknlMstpSrasWpstDnon",
				9.0200005,
				"AmovPknlMstpSrasWlnrDnon",
				9.0200005,
				"aadjpknlmstpsraswrflddown_amovpknlmstpsraswrfldnon",
				0.02,
				"aadjpknlmstpsraswrfldup_amovpknlmstpsraswrfldnon",
				0.02,
				"aadjpknlmstpsraswrfldright_amovpknlmstpsraswrfldnon",
				0.02,
				"aadjpknlmstpsraswrfldleft_amovpknlmstpsraswrfldnon",
				0.02
			};
			ConnectTo[]=
			{
				"AmovPknlMstpSoptWbinDnon",
				0.02,
				"AmovPknlMstpSnonWnonDnon",
				0.02,
				"AmovPknlMstpSrasWrflDnon",
				0.02,
				"AmovPknlMstpSlowWrflDnon",
				0.02,
				"AmovPknlMstpSlowWpstDnon",
				0.02,
				"AmovPknlMstpSrasWpstDnon",
				0.02,
				"AmovPknlMstpSrasWlnrDnon",
				0.02
			};
			showHandGun=0;
			showItemInRightHand=0;
		};
		class MOCAP_Idle_Prone_CivPace_Un_Prey_Lying_Neck_Twist_No_Contr: AmovPpneMstpSnonWnonDnon
		{
			file=QPATHTOF(Grabs\MOCAP_Idle_Prone_CivPace_Un_Prey_Lying_Neck_Twist_No_Contr.rtm);
			looped=0;
			speed=0.25;
			duty=2;
			mask="BodyFull";
			leftHandIKBeg=0;
			leftHandIKCurve[]={};
			leftHandIKEnd=0;
			rightHandIKBeg=0;
			rightHandIKCurve[]={};
			rightHandIKEnd=0;
			weaponIK=0;
			enableOptics=0;
			showWeaponAim=0;
			disableWeapons=1;
			disableWeaponsLong=1;
			leaning="empty";
			aimingBody="empty";
			aiming="empty";
			head="empty";
			forceAim=1;
			limitGunMovement=9.1000004;
			headBobMode=1;
			headBobStrength=0;
			canPullTrigger=0;
			enableDirectControl=0;
			variantsPlayer[]={};
			variantsAI[]={};
			ConnectFrom[]=
			{
				"ainvppnemstpsraswrfldnon",
				9.0200005,
				"AmovPpneMstpSoptWbinDnon",
				9.0200005,
				"AidlPpneMstpSnonWnonDnon_AI",
				9.0200005,
				"aidlppnemstpsraswrfldnon_ai",
				9.0200005,
				"AidlPpneMstpSrasWpstDnon_AI",
				9.0200005,
				"AmovPpneMstpSnonWnonDnon",
				9.0200005,
				"AmovPpneMstpSrasWrflDnon",
				9.0200005,
				"AmovPpneMstpSrasWpstDnon",
				9.0200005,
				"aadjppnemstpsraswpstddown",
				9.0200005,
				"aadjppnemstpsraswpstdleft",
				9.0200005,
				"aadjppnemstpsraswpstdright",
				9.0200005,
				"aadjppnemstpsraswrflddown",
				9.0200005,
				"aadjppnemstpsraswrfldleft",
				9.0200005,
				"aadjppnemstpsraswrfldright",
				9.0200005
			};
			ConnectTo[]=
			{
				"AmovPknlMstpSoptWbinDnon",
				0.02,
				"AmovPknlMstpSnonWnonDnon",
				0.02,
				"AmovPknlMstpSrasWrflDnon",
				0.02,
				"AmovPknlMstpSlowWrflDnon",
				0.02,
				"AmovPknlMstpSlowWpstDnon",
				0.02,
				"AmovPknlMstpSrasWpstDnon",
				0.02,
				"AmovPknlMstpSrasWlnrDnon",
				0.02
			};
			showHandGun=0;
			showItemInRightHand=0;
		};
	};
};
